
;import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByLabel('Login').click();
  await page.getByLabel('Login').fill('felipe25');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('daniel');
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Last Name').fill('diaz');
  await page.getByLabel('Password', { exact: true }).click();
  await page.getByLabel('Password', { exact: true }).press('CapsLock');
  await page.getByLabel('Password', { exact: true }).fill('D');
  await page.getByLabel('Password', { exact: true }).press('CapsLock');
  await page.getByLabel('Password', { exact: true }).fill('Daniel2021*');
  await page.getByLabel('Confirm Password').click();
  await page.getByLabel('Confirm Password').press('CapsLock');
  await page.getByLabel('Confirm Password').fill('D');
  await page.getByLabel('Confirm Password').press('CapsLock');
  await page.getByLabel('Confirm Password').fill('Daniel2021*');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByPlaceholder('Login').click();
  await page.getByPlaceholder('Login').click();
  await page.getByPlaceholder('Login').fill('felipe25');
  await page.getByRole('navigation').locator('input[name="password"]').click();
  await page.getByRole('navigation').locator('input[name="password"]').fill('Daniel2021*');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Profile' }).click();
  await page.getByLabel('Gender').click();
  await page.getByLabel('Gender').fill('Male');
  await page.getByLabel('Age', { exact: true }).click();
  await page.getByLabel('Age', { exact: true }).fill('20');
  await page.getByLabel('Address').click();
  await page.getByLabel('Address').fill('bosa calle 77');
  await page.getByLabel('Phone').click();
  await page.getByLabel('Phone').fill('3017277874');
  await page.getByRole('combobox', { name: 'Hobby' }).selectOption('Video Games');
  await page.getByLabel('Current Password').click();
  await page.getByLabel('Current Password').fill('Daniel2021*');
  await page.getByLabel('New Pasword').click();
  await page.getByLabel('New Pasword').press('CapsLock');
  await page.getByLabel('New Pasword').fill('F');
  await page.getByLabel('New Pasword').press('CapsLock');
  await page.getByLabel('New Pasword').fill('Felipe2022.');
  await page.getByLabel('Confirm Password').click();
  await page.getByLabel('Confirm Password').press('CapsLock');
  await page.getByLabel('Confirm Password').fill('F');
  await page.getByLabel('Confirm Password').press('CapsLock');
  await page.getByLabel('Confirm Password').fill('Felipe2022.');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByText('The profile has been saved successful').first().click();
});
